### ISSUE TITLE
box freeze after openWebif crash

### ISSUE THREAD

**Issue by vajkooo** [oe-alliance/OpenWebif#22]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Affected user interface (delete as appropriate):**
This bug occurs in *both* the `Modern` and `Classic` web interfaces.

**Describe the bug / Actual behaviour:**

After some time of streaming the box will freeze and you have to restart it. 

**Expected behaviour:**
not freeze

**Has this issue started to happen just recently?**
The problem started about a year ago

**To reproduce:**
Start streaming via 8001 port and normally watch the TV

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.

**Image (please complete the following information):**
OpenATV from 6.5
OpenBH 5.2
I tried a lot images and problem is in all of them

**Desktop (please complete the following information):**
doesnt matter

**Additional context**
here is message from debug log. 

<263644.5354> 09:12:03.8725
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/twisted/protocols/basic.py", line 549, in dataReceived

File "/usr/lib/python3.11/site-packages/twisted/web/http.py", line 2319, in lineReceived

File "/usr/lib/python3.11/site-packages/twisted/web/http.py", line 2447, in allContentReceived

File "/usr/lib/python3.11/site-packages/twisted/web/http.py", line 1032, in requestReceived

--- <exception caught here> ---
File "/usr/lib/python3.11/site-packages/twisted/web/server.py", line 227, in process

File "/usr/lib/python3.11/site-packages/twisted/web/server.py", line 292, in render

File "/ssd/jenkins_focal/workspace/settopbox-openbh-5.2/build-enviroment/builds/openbh/release/vuultimo4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-gitAUTOINC+bb61885253-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 237, in render

File "/ssd/jenkins_focal/workspace/settopbox-openbh-5.2/build-enviroment/builds/openbh/release/vuultimo4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-gitAUTOINC+bb61885253-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/utilities.py", line 278, in toBinary

builtins.MemoryError:
[Uploading Enigma2_debug_2023-06-05_19-12-59.log…]()

<263654.6255> 09:12:13.9732 [gRC] main thread is non-idle! display spinner!

**Comment by Huevos** [comment]
Port 8001 is a direct connection with enigma, nothing to do with OpenWebif.

You should report this on OpenBh forum.

**Comment by vajkooo** [comment]
check the log and tell me what causing the problem

**Comment by Huevos** [comment]
What hardware is it? The exception says the receiver is out of RAM.

**Comment by vajkooo** [comment]
> What hardware is it? The exception says the receiver is out of RAM.

sorry I forgot, it's VU+ ultimo 4K

**Comment by Huevos** [comment]
My guess is you were already out of RAM before this happened. What else do you have running on the box? LCD4Linux?

**Comment by vajkooo** [comment]
From packages LCD4Linux, nothing else. I disabled everything. What is just running is streaming to android TV in other room.

**Comment by Huevos** [comment]
You need to remove LCD4Linux and try again.

**Comment by vajkooo** [comment]
hi I uninstalled all plugins but still same problem. I'm attaching the last log. 
[Enigma2_debug_2023-06-07_11-18-45.log](https://github.com/oe-alliance/OpenWebif/files/11785063/Enigma2_debug_2023-06-07_11-18-45.log)

**Comment by jbleyel** [comment]
This is not an Openwebif issue.
